### PR TITLE
Use getHostName() to determine the host name as opposed to serverstatus.host

### PR DESCRIPTION
**Pull request by tomruggs**
The docs say that db.serverStatus().host -should- be the same as getHostName() but that is not what I see locally and what it is returning for me is incorrect where getHostName() is correct.  I suspect that the former may be where the server was compiled and the latter is where it is actually running.

### CODE REVIEW

**Comment by TylerBrock** [comment]
Hey Tom, thanks for the pull request and the message. The difference is that getHostName() retrieves the hostname of the client NOT the MongoDB server you are connected to which is the intent of the prompt here. The rest of the prompt components (the name of the replica set, etc...) are all about the server you are connected to and not where the connection is coming from.

**Comment by tomruggs** [comment]
Then I'm perplexed.  My Mongo console and server are both running on my local machine.  Here's what I see:

```
$ hostname
truggles-retina-5.local

$ uname -n
truggles-retina-5.local

$ mongo
MongoDB shell version: 2.4.2
connecting to: test
Mongo-Hacker 0.0.4

truggles-retina-5(mongod-2.4.2) test> db.serverStatus().host
lleborgne-think.vidmark.local

truggles-retina-5(mongod-2.4.2) test> getHostName()
truggles-retina-5.local
```

Notice that db.serverStatus() does not match.

**Comment by tomruggs** [comment]
Installing mongodb via brew made its db.serverStatus().host correct.  Idk.  Closing.

**Comment by TylerBrock** [comment]
Ok, cool. Maybe its because 2.6.x is better at detecting hostnames than 2.4.x

**Pull request closed without merging**
