### PR TITLE
Fix #119: More standard behaviour for `make`

### LINKED ISSUE #119: More standard behaviour for `make`
Several times I've accidentally run "make" to build the updated script without wanting to replace my `~/.mongorc.js`.

I think more standard behaviour would be:
 - `make` - build `mongo_hacker.js`
 - `make all` - same as default make
 - `make clean` - remove `mongo_hacker.js`
 - `make install` - actually install

### PR DESCRIPTION
**Pull request by stennie**

### CODE REVIEW

**Comment by TylerBrock** [comment]
Thanks stennie, I like it. Can you update the readme to reflect the change?

**Comment by TylerBrock** [comment]
Also the package.json file needs updating if we merge this as well.

**Comment by stennie** [comment]
@TylerBrock Thanks .. missed the `package.json` reference as I've been installing via make. Tidied up including readme.

**Comment by TylerBrock** [comment]
Sweet, thanks.

**Pull request merged**
